/* eslint-disable max-len */
export const SHOWCASE_LINKS = {
  // AXES SHOW CASE LINKS
  AxisOn0:
    'https://github.com/uber/react-vis/blob/master/showcase/axes/axis-on-0.js',
  CustomAxesOrientation:
    'https://github.com/uber/react-vis/blob/master/showcase/axes/custom-axes-orientation.js',
  CustomAxisChart:
    'https://github.com/uber/react-vis/blob/master/showcase/axes/custom-axis.js',
  CustomAxes:
    'https://github.com/uber/react-vis/blob/master/showcase/axes/custom-axes.js',
  AxisWithTurnedLabels:
    'https://github.com/uber/react-vis/blob/master/showcase/plot/axis-with-turned-labels.js',
  PaddedAxis:
    'https://github.com/uber/react-vis/blob/master/showcase/axes/padded-axis.js',
  // AXES - TOOLTIPS SHOW CASE LINKS
  StaticHints:
    'https://github.com/uber/react-vis/blob/master/showcase/axes/static-hints.js',
  DynamicHints:
    'https://github.com/uber/react-vis/blob/master/showcase/axes/dynamic-hints.js',
  DynamicSimpleEdgeHints:
    'https://github.com/uber/react-vis/blob/master/showcase/axes/dynamic-simple-edge-hints.js',
  DynamicSimpleTopEdgeHints:
    'https://github.com/uber/react-vis/blob/master/showcase/axes/dynamic-simple-topedge-hints.js',
  DynamicProgrammaticRightEdgeHints:
    'https://github.com/uber/react-vis/blob/master/showcase/axes/dynamic-programmatic-rightedge-hints.js',
  DynamicComplexEdgeHints:
    'https://github.com/uber/react-vis/blob/master/showcase/axes/dynamic-complex-edge-hints.js',
  StaticCrosshair:
    'https://github.com/uber/react-vis/blob/master/showcase/axes/static-crosshair.js',
  DynamicCrosshair:
    'https://github.com/uber/react-vis/blob/master/showcase/axes/dynamic-crosshair.js',
  DynamicCrosshairScatterplot:
    'https://github.com/uber/react-vis/blob/master/showcase/axes/dynamic-crosshair-scatterplot.js',
  // AXES - DECORATIVE_AXES SHOWCASE LINKS
  DecorativeAxisCrissCross:
    'https://github.com/uber/react-vis/blob/master/showcase/axes/decorative-axes-criss-cross.js',
  ParallelCoordinatesExample:
    'https://github.com/uber/react-vis/blob/master/showcase/axes/parallel-coordinates-example.js',
  // MISC SHOWCASE LINKS
  SyncedCharts:
    'https://github.com/uber/react-vis/blob/master/showcase/misc/synced-charts.js',
  TimeChart:
    'https://github.com/uber/react-vis/blob/master/showcase/misc/time-chart.js',
  TriangleExample:
    'https://github.com/uber/react-vis/blob/master/showcase/misc/triangle-example.js',
  VoronoiLineChart:
    'https://github.com/uber/react-vis/blob/master/showcase/misc/voronoi-line-chart.js',
  GradientExample:
    'https://github.com/uber/react-vis/blob/master/showcase/misc/gradient-example.js',
  AnimationExample:
    'https://github.com/uber/react-vis/blob/master/showcase/misc/animation-example.js',
  LabelSeriesExample:
    'https://github.com/uber/react-vis/blob/master/showcase/misc/label-series-example.js',
  NullDataExample:
    'https://github.com/uber/react-vis/blob/master/showcase/misc/null-data-example.js',
  ZoomableChartExample:
    'https://github.com/uber/react-vis/blob/master/showcase/misc/zoomable-chart-example.js',
  SelectionPlotExample:
    'https://github.com/uber/react-vis/blob/master/showcase/misc/selection-plot-example.js',
  DragableChartExample:
    'https://github.com/uber/react-vis/blob/master/showcase/misc/dragable-chart-example.js',
  BidirectionDragChart:
    'https://github.com/uber/react-vis/blob/master/showcase/misc/2d-dragable-plot.js',
  // PARALLEL COORDS LINKS
  BasicParallelCoordinates:
    'https://github.com/uber/react-vis/blob/master/showcase/parallel-coordinates/animated-parallel-coordinates.js',
  AnimatedParallelCoordinates:
    'https://github.com/uber/react-vis/blob/master/showcase/parallel-coordinates/basic-parallel-coordinates.js',
  // PLOTS SHOWCASE LINKES
  LineChart:
    'https://github.com/uber/react-vis/blob/master/showcase/plot/line-chart.js',
  LineChartWithStyle:
    'https://github.com/uber/react-vis/blob/master/showcase/plot/line-chart-with-style.js',
  LineMarkChart:
    'https://github.com/uber/react-vis/blob/master/showcase/plot/linemark-chart.js',
  LineChartCanvas:
    'https://github.com/uber/react-vis/blob/master/showcase/plot/line-chart-canvas.js',
  LineChartManyColors:
    'https://github.com/uber/react-vis/blob/master/showcase/color/line-chart-many-colors.js',
  ScatterplotChart:
    'https://github.com/uber/react-vis/blob/master/showcase/plot/scatterplot.js',
  ScatterplotCanvas:
    'https://github.com/uber/react-vis/blob/master/showcase/plot/scatterplot-canvas.js',
  WhiskerChart:
    'https://github.com/uber/react-vis/blob/master/showcase/plot/whisker-chart.js',
  AreaChart:
    'https://github.com/uber/react-vis/blob/master/showcase/plot/area-chart.js',
  AreaChartElevated:
    'https://github.com/uber/react-vis/blob/master/showcase/plot/area-chart-elevated.js',
  BarChart:
    'https://github.com/uber/react-vis/blob/master/showcase/plot/bar-chart.js',
  BigBaseBarChart:
    'https://github.com/uber/react-vis/blob/master/showcase/plot/big-base-bar-chart.js',
  StackedHorizontalBarChart:
    'https://github.com/uber/react-vis/blob/master/showcase/plot/stacked-horizontal-bar-chart.js',
  StackedVerticalBarChart:
    'https://github.com/uber/react-vis/blob/master/showcase/plot/stacked-vertical-bar-chart.js',
  ClusteredStackedVerticalBarChart:
    'https://github.com/uber/react-vis/blob/master/showcase/plot/clustered-stacked-bar-chart.js',
  StackedHistogram:
    'https://github.com/uber/react-vis/blob/master/showcase/plot/stacked-histogram.js',
  Histogram:
    'https://github.com/uber/react-vis/blob/master/showcase/plot/histogram.js',
  HeatmapChart:
    'https://github.com/uber/react-vis/blob/master/showcase/plot/heatmap-chart.js',
  HexHeatmap:
    'https://github.com/uber/react-vis/blob/master/showcase/plot/hex-heatmap.js',
  HexbinSizeExample:
    'https://github.com/uber/react-vis/blob/master/showcase/plot/hexbin-size-example.js',
  LabeledHeatmap:
    'https://github.com/uber/react-vis/blob/master/showcase/plot/labeled-heatmap.js',
  ContourSeriesExample:
    'https://github.com/uber/react-vis/blob/master/showcase/plot/contour-series-example.js',
  CustomSVGExample:
    'https://github.com/uber/react-vis/blob/master/showcase/plot/custom-svg-example.js',
  CustomSVGAllTheMarks:
    'https://github.com/uber/react-vis/blob/master/showcase/plot/custom-svg-all-the-marks.js',
  CustomSVGRootLevel:
    'https://github.com/uber/react-vis/blob/master/showcase/plot/custom-svg-root-level.js',
  // BASIC COMPONENTS SHOWCASE LINKS
  WidthHeightMarginChart:
    'https://github.com/uber/react-vis/blob/master/showcase/plot/width-height-margin.js',
  CustomScales:
    'https://github.com/uber/react-vis/blob/master/showcase/plot/custom-scales.js',
  GridLinesChart:
    'https://github.com/uber/react-vis/blob/master/showcase/plot/grid.js',
  FauxScatterplotChart:
    'https://github.com/uber/react-vis/blob/master/showcase/plot/faux-radial-scatterplot.js',
  EmptyChart:
    'https://github.com/uber/react-vis/blob/master/showcase/plot/empty-chart.js',
  // RADAR CHART SHOWCASE LINKS
  AnimatedRadarChart:
    'https://github.com/uber/react-vis/blob/master/showcase/radar-chart/animated-radar-chart.js',
  BasicRadarChart:
    'https://github.com/uber/react-vis/blob/master/showcase/radar-chart/basic-radar-chart.js',
  FourQuadrantRadarChart:
    'https://github.com/uber/react-vis/blob/master/showcase/radar-chart/four-quadrant-radar-chart.js',
  RadarChartWithTooltips:
    'https://github.com/uber/react-vis/blob/master/showcase/radar-chart/radar-chart-with-tooltips.js',
  RadarChartSeriesTooltips:
    'https://github.com/uber/react-vis/blob/master/showcase/radar-chart/radar-chart-series-tooltips.js',

  // RADIAL CHART SHOWCASE LINKS
  SimpleRadialChart:
    'https://github.com/uber/react-vis/blob/master/showcase/radial-chart/simple-radial-chart.js',
  GradientPie:
    'https://github.com/uber/react-vis/blob/master/showcase/radial-chart/gradient-pie.js',
  DonutChartExample:
    'https://github.com/uber/react-vis/blob/master/showcase/radial-chart/donut-chart.js',
  CustomRadiusRadialChart:
    'https://github.com/uber/react-vis/blob/master/showcase/radial-chart/custom-radius-radial-chart.js',
  // SANKEY SHOWCASE LINKS
  BasicSankeyExample:
    'https://github.com/uber/react-vis/blob/master/showcase/sankey/basic.js',
  VoronoiSankeyExample:
    'https://github.com/uber/react-vis/blob/master/showcase/sankey/voronoi.js',
  LinkEventSankeyExample:
    'https://github.com/uber/react-vis/blob/master/showcase/sankey/link-event.js',
  LinkHintSankeyExample:
    'https://github.com/uber/react-vis/blob/master/showcase/sankey/link-hint.js',
  EnergySankeyExample:
    'https://github.com/uber/react-vis/blob/master/showcase/sankey/energy-sankey.js',
  // SUNBURST SHOWCASE LINKS
  ArcSeriesExample:
    'https://github.com/uber/react-vis/blob/master/showcase/radial-chart/arc-series-example.js',
  BasicSunburst:
    'https://github.com/uber/react-vis/blob/master/showcase/sunbursts/basic-sunburst.js',
  ClockExample:
    'https://github.com/uber/react-vis/blob/master/showcase/sunbursts/clock-example.js',
  AnimatedSunburst:
    'https://github.com/uber/react-vis/blob/master/showcase/sunbursts/animated-sunburst.js',
  SunburstWithTooltips:
    'https://github.com/uber/react-vis/blob/master/showcase/sunbursts/sunburst-with-tooltips.js',
  // TREEMAP SHOWCASE LINKS
  SimpleTreemap:
    'https://github.com/uber/react-vis/blob/master/showcase/treemap/simple-treemap.js',
  TreemapExample:
    'https://github.com/uber/react-vis/blob/master/showcase/treemap/dynamic-treemap.js',
  // LEGENDS SHOWCASE LINKS
  VerticalDiscreteColorLegendExample:
    'https://github.com/uber/react-vis/blob/master/showcase/legends/vertical-discrete-color.js',
  HorizontalDiscreteColorLegendExample:
    'https://github.com/uber/react-vis/blob/master/showcase/legends/horizontal-discrete-color.js',
  HorizontalDiscreteCustomPalette:
    'https://github.com/uber/react-vis/blob/master/showcase/legends/horizontal-discrete-custom-palette.js',
  SearchableDiscreteColorLegendExample:
    'https://github.com/uber/react-vis/blob/master/showcase/legends/searchable-discrete-color.js',
  ContinuousColorLegendExample:
    'https://github.com/uber/react-vis/blob/master/showcase/legends/continuous-color.js',
  ContinuousSizeLegendExample:
    'https://github.com/uber/react-vis/blob/master/showcase/legends/continuous-size.js'
};
/* eslint-enable max-len */
